
- name: "Provision instance"
  environment: 
    GIT_PYTHON_REFRESH: quiet
  command: "{{ venv }}/bin/awx-manage  provision_instance --hostname={{ ansible_hostname }}"
  args:
    chdir: "{{ destination }}"
  register: migrate_cmd
  failed_when: migrate_cmd.rc == 1
  changed_when: migrate_cmd.rc == 0
  become_user: "{{ awx_user }}"
  become: True

- name: "Register quename"
  environment: 
    GIT_PYTHON_REFRESH: quiet
  command: "{{ venv }}/bin/awx-manage  register_queue --queuename=tower --hostname={{ ansible_hostname }}"
  args:
    chdir: "{{ destination }}"
  register: migrate_cmd
  failed_when: migrate_cmd.rc == 1
  changed_when: migrate_cmd.rc == 0
  become_user: "{{ awx_user }}"
  become: True