- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: latest
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: depend | Ensure dependencies are installed.
  dnf:
    pkg: [
                'jq',
                'redis',
                'nginx',
                'git',
                'python3-virtualenv',
                'gcc-c++',
                'npm',
                'device-mapper-persistent-data',
                'lvm2',
                'bzip2',
                'python3-pip',
                'ansible',
                'gcc',
                'openldap-devel',
                'xmlsec1-openssl',
                '@Development Tools',
                'python3.8',
                'ansible-collection-ansible-posix',
                'supervisor'
                
        ]
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install add  packages
  yum:
    name:
      - xmlsec1-devel
      - libtool-ltdl-devel
      - mlocate
      - libpq-devel

    state: latest
    enablerepo: "powertools"
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: Add the group 'awx' with a specific gid and
  ansible.builtin.group:
    name: "{{ awx_user }}"
    state: present
    gid: 1666
  become: True

- name: Add the user 'awx' with a specific uid and a primary group of 'awx'
  ansible.builtin.user:
    name: "{{ awx_user }}" 
    comment: awx service accout
    uid: 1666
    group: "{{ awx_user }}"
  become: true 

- name: Create log dir
  file:
    path: /var/log/tower
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: true

- name: Create  /var/lib/awx/rsyslog
  file:
    path: /var/lib/awx/rsyslog
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: true

- name: Create awx home
  file:
    path: /var/lib/awx
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: true

- name: Git checkout awx
  ansible.builtin.git:
    repo: 'https://github.com/ansible/awx.git'
    dest: "/tmp/awx/{{ awx_image_version }}"
    version: "{{ awx_image_version }}"
    force: True
  become: True
  become_user: "{{ awx_user }}"

- name: Recursively change ownership of the directory /etc/tower/conf.d
  ansible.builtin.file:
    path: /etc/tower/conf.d
    state: directory
    recurse: yes
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
  become: True


- name: set owener /run/tower
  ansible.builtin.file:
    path: /run/tower
    state: directory
    owner: "{{ awx_user }}"
    group: nginx
  become: True

- name: Recursirely change ownership of the directory /tmp/awx
  ansible.builtin.file:
    path: /tmp/awx
    state: directory
    recurse: yes
    owner: "{{ awx_user }}"
    group: "{{ awx_user }}"
  become: True

- name:  create venv
  ansible.builtin.pip:
    requirements: /tmp/awx/requirements/requirements.txt
    virtualenv: "{{ venv }}"
    virtualenv_command: /usr/bin/python3 -m venv
  become_user: "{{ awx_user }}"
  become: True

#- name: create checkplatform script
#  template:
#    src: checkplatform.sh.j2
#    dest: /usr/local/bin/checkplatform.sh
#    force: yes
#    mode: '0770'
#    owner: awx
#    group: awx
#  become: True

- name: Enable SELinux in enforcing mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: True

- name: "adding nginx to group {{ awx_user }}"
  user:
    name: nginx
    groups: "{{ awx_user }}"
    append: yes
  become: True
